set_property SRC_FILE_INFO {cfile:c:/Users/Lenovo/Desktop/zynq7020-image-processing/sobel_03_uart_hdmi/sobel_03_uart_hdmi.srcs/sources_1/ip/video_clock/video_clock.xdc rfile:../../../sobel_03_uart_hdmi.srcs/sources_1/ip/video_clock/video_clock.xdc id:1 order:EARLY scoped_inst:hdmi_pl_top_i/video_clock_m0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/Lenovo/Desktop/zynq7020-image-processing/sobel_03_uart_hdmi/sobel_03_uart_hdmi.srcs/constrs_1/new/hdmi_out_test.xdc rfile:../../../sobel_03_uart_hdmi.srcs/constrs_1/new/hdmi_out_test.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.2
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports {sys_clk}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V13 [get_ports TMDS_clk_n]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U13 [get_ports TMDS_clk_p]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y14 [get_ports {TMDS_data_n[0]}]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W14 [get_ports {TMDS_data_p[0]}]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y19 [get_ports {TMDS_data_n[1]}]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y18 [get_ports {TMDS_data_p[1]}]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports {TMDS_data_n[2]}]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports {TMDS_data_p[2]}]
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports hdmi_oen]
